/**
 * Created by weishuwen on 2015/3/5.
 */

define(function(require, exports, module) {

    var item = [
        {
            "id": 9339434,
            "sceneId": 712959,
            "num": 1,
            "name": "第1页",
            "properties": null,
            "elements": [
                {
                    "id": 63620385,
                    "pageId": 9339434,
                    "sceneId": 712959,
                    "type": "2",
                    "isInput": 0,
                    "title": null,
                    "content": '../css/image/dog.jpeg',
                    "status": 1,
                    "css": {
                        "background": "rgb(255,255,255)",
                        "opacity": 100,
                        "borderRadius": "10",
                        "transform": "350",
                        "borderType": "solid",
                        "borderWidth": "2px",
                        "borderColor": "rgb(220,0,0)",
                        "shadowSize": 2,
                        "shadowOffset": 3,
                        "shadowColor": "rgb(10,0,0)",
                        "animateType": "bounceIn",
                        "animateTime": 2,
                        "animateDelay": 0,
                        "animateTimes": 4,
                        "animateInfinite": false,

                        "zIndex": "555555",
                        "color": "",
                        "width": "105",
                        "height": "70",
                        "left": "46",
                        "top": "64"
                    }
                },
                {
                    "id": 63620386,
                    "pageId": 9339434,
                    "sceneId": 712959,
                    "type": "2",
                    "isInput": 0,
                    "title": null,
                    "content": '../css/image/dog.jpeg',
                    "status": 1,
                    "css": {
                        "background": "rgb(255,255,255)",
                        "opacity": 100,
                        "borderRadius": "4",
                        "transform": "0",
                        "borderType": "solid",
                        "borderWidth": "2px",
                        "borderColor": "rgb(220,0,0)",
                        "shadowSize": 2,
                        "shadowOffset": 3,
                        "shadowColor": "rgb(10,0,0)",
                        "animateType": "",
                        "animateTime": 2,
                        "animateDelay": 0,
                        "animateTimes": 2,
                        "animateInfinite": false,

                        "zIndex": "555555",
                        "color": "",
                        "width": "105",
                        "height": "30",
                        "left": "146",
                        "top": "264"
                    }
                },
                {
                    "id": 63620387,
                    "pageId": 9339434,
                    "sceneId": 712959,
                    "type": "2",
                    "isInput": 0,
                    "title": null,
                    "content": '../css/image/bg.jpg',
                    "status": 1,
                    "css": {
                        "background": "rgb(255,255,255)",
                        "opacity": 100,
                        "borderRadius": "4",
                        "transform": "0",
                        "borderType": "solid",
                        "borderWidth": "2px",
                        "borderColor": "rgb(220,0,0)",
                        "shadowSize": 2,
                        "shadowOffset": 3,
                        "shadowColor": "rgb(10,0,0)",
                        "animateType": "",
                        "animateTime": 2,
                        "animateDelay": 0,
                        "animateTimes": 2,
                        "animateInfinite": false,

                        "zIndex": "555555",
                        "color": "",
                        "width": "155",
                        "height": "70",
                        "left": "146",
                        "top": "94"
                    }
                }],
            "scene": {
                "id": 712959,
                "name": "2222",
                "createUser": "4a2d8aae4b14dcd7014b294902a64c24",
                "createTime": 1422327309000,
                "type": 1,
                "pageMode": 2,
                "image": {
                    "imgSrc": "../css/image/bg.jpg",
                    "background": false
                },
                "isTpl": 0,
                "isPromotion": 0,
                "status": 1,
                "openLimit": 0,
                "submitLimit": 0,
                "startDate": null,
                "endDate": null,
                "accessCode": null,
                "thirdCode": null,
                "updateTime": 1422344387000,
                "publishTime": 1422344387000,
                "applyTemplate": 0,
                "applyPromotion": 0,
                "sourceId": null,
                "code": "oRy7T2",
                "description": null,
                "sort": 0,
                "pageCount": 0,
                "dataCount": 0,
                "showCount": 0,
                "userLoginName": null,
                "userName": null
            }
        },
        {
            "id": 9339434,
            "sceneId": 712959,
            "num": 1,
            "name": "第2页",
            "properties": null,
            "elements": [
                {
                    "id": 63620385,
                    "pageId": 9339434,
                    "sceneId": 712959,
                    "type": "2",
                    "isInput": 0,
                    "title": null,
                    "content": '../css/image/dog.jpeg',
                    "status": 1,
                    "css": {
                        "background": "rgb(255,255,255)",
                        "opacity": 100,
                        "borderRadius": "4",
                        "transform": "350",
                        "borderType": "solid",
                        "borderWidth": "2",
                        "borderColor": "rgb(220,0,0)",
                        "shadowSize": 3,
                        "shadowOffset": 3,
                        "shadowColor": "rgb(10,0,0)",
                        "animateType": "bounceIn",
                        "animateTime": 2,
                        "animateDelay": 0,
                        "animateTimes": 2,
                        "animateInfinite": false,

                        "zIndex": "555555",
                        "color": "",
                        "width": "105",
                        "height": "70",
                        "left": "46",
                        "top": "64"
                    }
                },
                {
                    "id": 63620386,
                    "pageId": 9339434,
                    "sceneId": 712959,
                    "type": "2",
                    "isInput": 0,
                    "title": null,
                    "content": '../css/image/dog.jpeg',
                    "status": 1,
                    "css": {
                        "background": "rgb(255,255,255)",
                        "opacity": 100,
                        "borderRadius": "4",
                        "transform": "0",
                        "borderType": "solid",
                        "borderWidth": "2",
                        "borderColor": "rgb(220,0,0)",
                        "shadowSize": 3,
                        "shadowOffset": 3,
                        "shadowColor": "rgb(10,0,0)",
                        "animateType": "",
                        "animateTime": 0,
                        "animateDelay": 0,
                        "animateTimes": 0,
                        "animateInfinite": false,

                        "zIndex": "555555",
                        "color": "",
                        "width": "105",
                        "height": "30",
                        "left": "146",
                        "top": "264"
                    }
                },
                {
                    "id": 63620387,
                    "pageId": 9339434,
                    "sceneId": 712959,
                    "type": "2",
                    "isInput": 0,
                    "title": null,
                    "content": '../css/image/bg.jpg',
                    "status": 1,
                    "css": {
                        "background": "rgb(255,255,255)",
                        "opacity": 100,
                        "borderRadius": "4",
                        "transform": "0",
                        "borderType": "solid",
                        "borderWidth": "2",
                        "borderColor": "rgb(220,0,0)",
                        "shadowSize": 3,
                        "shadowOffset": 3,
                        "shadowColor": "rgb(10,0,0)",
                        "animateType": "",
                        "animateTime": 0,
                        "animateDelay": 0,
                        "animateTimes": 0,
                        "animateInfinite": false,

                        "zIndex": "555555",
                        "color": "",
                        "width": "155",
                        "height": "70",
                        "left": "146",
                        "top": "94"
                    }
                }],
            "scene": {
                "id": 712959,
                "name": "2222",
                "createUser": "4a2d8aae4b14dcd7014b294902a64c24",
                "createTime": 1422327309000,
                "type": 1,
                "pageMode": 2,
                "image": {
                    "imgSrc": "../css/image/bg2.jpg",
                    "background": false
                },
                "isTpl": 0,
                "isPromotion": 0,
                "status": 1,
                "openLimit": 0,
                "submitLimit": 0,
                "startDate": null,
                "endDate": null,
                "accessCode": null,
                "thirdCode": null,
                "updateTime": 1422344387000,
                "publishTime": 1422344387000,
                "applyTemplate": 0,
                "applyPromotion": 0,
                "sourceId": null,
                "code": "oRy7T2",
                "description": null,
                "sort": 0,
                "pageCount": 0,
                "dataCount": 0,
                "showCount": 0,
                "userLoginName": null,
                "userName": null
            }
        },
        {
            "id": 9339434,
            "sceneId": 712959,
            "num": 1,
            "name": "第3页",
            "properties": null,
            "elements": [
                {
                    "id": 63620385,
                    "pageId": 9339434,
                    "sceneId": 712959,
                    "type": "2",
                    "isInput": 0,
                    "title": null,
                    "content": '../css/image/dog.jpeg',
                    "status": 1,
                    "css": {
                        "background": "rgb(255,255,255)",
                        "opacity": 100,
                        "borderRadius": "4",
                        "transform": "350",
                        "borderType": "solid",
                        "borderWidth": "2px",
                        "borderColor": "rgb(220,0,0)",
                        "shadowSize": 3,
                        "shadowOffset": 3,
                        "shadowColor": "rgb(10,0,0)",
                        "animateType": "fadeIn",
                        "animateTime": 2,
                        "animateDelay": 0,
                        "animateTimes": 2,
                        "animateInfinite": false,

                        "zIndex": "555555",
                        "color": "",
                        "width": "105",
                        "height": "70",
                        "left": "46",
                        "top": "64"
                    }
                },
                {
                    "id": 63620386,
                    "pageId": 9339434,
                    "sceneId": 712959,
                    "type": "2",
                    "isInput": 0,
                    "title": null,
                    "content": '../css/image/dog.jpeg',
                    "status": 1,
                    "css": {
                        "background": "rgb(255,255,255)",
                        "opacity": 100,
                        "borderRadius": "4",
                        "transform": "0",
                        "borderType": "solid",
                        "borderWidth": "2px",
                        "borderColor": "rgb(220,0,0)",
                        "shadowSize": 3,
                        "shadowOffset": 3,
                        "shadowColor": "rgb(10,0,0)",
                        "animateType": "",
                        "animateTime": 0,
                        "animateDelay": 0,
                        "animateTimes": 0,
                        "animateInfinite": false,

                        "zIndex": "555555",
                        "color": "",
                        "width": "105",
                        "height": "30",
                        "left": "146",
                        "top": "264"
                    }
                },
                {
                    "id": 63620387,
                    "pageId": 9339434,
                    "sceneId": 712959,
                    "type": "2",
                    "isInput": 0,
                    "title": null,
                    "content": '../css/image/bg.jpg',
                    "status": 1,
                    "css": {
                        "background": "rgb(255,255,255)",
                        "opacity": 100,
                        "borderRadius": "4",
                        "transform": "0",
                        "borderType": "solid",
                        "borderWidth": "2px",
                        "borderColor": "rgb(220,0,0)",
                        "shadowSize": 3,
                        "shadowOffset": 3,
                        "shadowColor": "rgb(10,0,0)",
                        "animateType": "",
                        "animateTime": 0,
                        "animateDelay": 0,
                        "animateTimes": 0,
                        "animateInfinite": false,

                        "zIndex": "555555",
                        "color": "",
                        "width": "155",
                        "height": "70",
                        "left": "146",
                        "top": "94"
                    }
                }],
            "scene": {
                "id": 712959,
                "name": "2222",
                "createUser": "4a2d8aae4b14dcd7014b294902a64c24",
                "createTime": 1422327309000,
                "type": 1,
                "pageMode": 2,
                "image": {
                    "imgSrc": "../css/image/bg1.jpg",
                    "background": false
                },
                "isTpl": 0,
                "isPromotion": 0,
                "status": 1,
                "openLimit": 0,
                "submitLimit": 0,
                "startDate": null,
                "endDate": null,
                "accessCode": null,
                "thirdCode": null,
                "updateTime": 1422344387000,
                "publishTime": 1422344387000,
                "applyTemplate": 0,
                "applyPromotion": 0,
                "sourceId": null,
                "code": "oRy7T2",
                "description": null,
                "sort": 0,
                "pageCount": 0,
                "dataCount": 0,
                "showCount": 0,
                "userLoginName": null,
                "userName": null
            }
        },
        {
            "id": 9339434,
            "sceneId": 712959,
            "num": 1,
            "name": "第4页",
            "properties": null,
            "elements": [
                {
                    "id": 63620385,
                    "pageId": 9339434,
                    "sceneId": 712959,
                    "type": "2",
                    "isInput": 0,
                    "title": null,
                    "content": '../css/image/dog.jpeg',
                    "status": 1,
                    "css": {
                        "background": "rgb(255,255,255)",
                        "opacity": 100,
                        "borderRadius": "4",
                        "transform": "350",
                        "borderType": "solid",
                        "borderWidth": "2px",
                        "borderColor": "rgb(220,0,0)",
                        "shadowSize": 3,
                        "shadowOffset": 3,
                        "shadowColor": "rgb(10,0,0)",
                        "animateType": "fadeIn",
                        "animateTime": 2,
                        "animateDelay": 0,
                        "animateTimes": 2,
                        "animateInfinite": false,

                        "zIndex": "555555",
                        "color": "",
                        "width": "105",
                        "height": "70",
                        "left": "46",
                        "top": "64"
                    }
                },
                {
                    "id": 63620386,
                    "pageId": 9339434,
                    "sceneId": 712959,
                    "type": "2",
                    "isInput": 0,
                    "title": null,
                    "content": '../css/image/dog.jpeg',
                    "status": 1,
                    "css": {
                        "background": "rgb(255,255,255)",
                        "opacity": 100,
                        "borderRadius": "4",
                        "transform": "0",
                        "borderType": "solid",
                        "borderWidth": "2px",
                        "borderColor": "rgb(220,0,0)",
                        "shadowSize": 3,
                        "shadowOffset": 3,
                        "shadowColor": "rgb(10,0,0)",
                        "animateType": "",
                        "animateTime": 2,
                        "animateDelay": 0,
                        "animateTimes": 2,
                        "animateInfinite": false,

                        "zIndex": "555555",
                        "color": "",
                        "width": "105",
                        "height": "30",
                        "left": "146",
                        "top": "264"
                    }
                },
                {
                    "id": 63620387,
                    "pageId": 9339434,
                    "sceneId": 712959,
                    "type": "2",
                    "isInput": 0,
                    "title": null,
                    "content": '../css/image/bg.jpg',
                    "status": 1,
                    "css": {
                        "background": "rgb(255,255,255)",
                        "opacity": 100,
                        "borderRadius": "4",
                        "transform": "0",
                        "borderType": "solid",
                        "borderWidth": "2px",
                        "borderColor": "rgb(220,0,0)",
                        "shadowSize": 3,
                        "shadowOffset": 3,
                        "shadowColor": "rgb(10,0,0)",
                        "animateType": "",
                        "animateTime": 2,
                        "animateDelay": 0,
                        "animateTimes": 2,
                        "animateInfinite": false,

                        "zIndex": "555555",
                        "color": "",
                        "width": "155",
                        "height": "70",
                        "left": "146",
                        "top": "94"
                    }
                }],
            "scene": {
                "id": 712959,
                "name": "2222",
                "createUser": "4a2d8aae4b14dcd7014b294902a64c24",
                "createTime": 1422327309000,
                "type": 1,
                "pageMode": 2,
                "image": {
                    //"imgSrc": "../css/image/bg.jpg",
                    "background": "blue"
                },
                "isTpl": 0,
                "isPromotion": 0,
                "status": 1,
                "openLimit": 0,
                "submitLimit": 0,
                "startDate": null,
                "endDate": null,
                "accessCode": null,
                "thirdCode": null,
                "updateTime": 1422344387000,
                "publishTime": 1422344387000,
                "applyTemplate": 0,
                "applyPromotion": 0,
                "sourceId": null,
                "code": "oRy7T2",
                "description": null,
                "sort": 0,
                "pageCount": 0,
                "dataCount": 0,
                "showCount": 0,
                "userLoginName": null,
                "userName": null
            }
        }
    ];

    console.log(localStorage.getItem('scene'));

    var item = JSON.parse(localStorage.getItem('scene')) || [];

    module.exports = {
        item: item
    }

});